<p id="admin-nav"><a lang="loginTitle" href="<?php echo $this->url('admin/index'); ?>"></a>--<span lang="page"></span></p>
<div id="page_contents_main">
	<?php if (count($this->paginator)): ?>
	<table cellspacing="0" id="table_for_opration">
	<tr>
	<td valign="middle"><input type="checkbox" id="cba" /></td>
	<td lang="pageTitle" valign="middle"></td>
	<td lang="createTime" valign="middle"></td>
	<td lang="updateTime" valign="middle"></td>
	<td valign="middle"></td>
	</tr>
	<?php foreach($this->paginator as $data): ?>
	<tr>
	<td valign="middle"><input class="table-checkbox" type="checkbox" value="<?php echo $this->viewHelper->string('page_id',$data); ?>"/></td>
	<td valign="middle"><?php echo $this->viewHelper->string('page_title',$data); ?></td>
	<td valign="middle"><?php echo $this->viewHelper->dataFormatter('create_time','Y-m-d H:i:s',$data); ?></td>
	<td valign="middle"><?php echo $this->viewHelper->dataFormatter('update_time','Y-m-d H:i:s',$data); ?></td>
	<td valign="middle">
	    <a lang="edit" href="<?php echo $this->url('admin/page/edit',array('pId' => $this->viewHelper->string('page_id',$data))); ?>"></a>
	    <a lang="show" href="<?php echo $this->url('admin/page/show',array('pId' => $this->viewHelper->string('page_id',$data))); ?>"></a>
	</td>
	</tr>
	<?php endforeach; ?>
	</table>
	<form id="delete-form" action="<?php echo $this->url('admin/page/delete') ?>" method="post">
		<input id="delete-button" style="margin-top:10px;" type="button" />
	</form>
	<?php endif; ?>
	<?php echo $this->paginationControl($this->paginator,'Elastic','admin/common/pagination',array('route' => 'admin/page/index')); ?>
</div>
<script type="text/javascript" src="/js/admin/page_index.js"></script>