<div id="page_contents_main">
	<table cellspacing="0" id="table_for_opration">
	<tr>
	<td valign="middle"><input type="checkbox" id="cba" /></td>
	<td valign="middle">商品编号</td>
	<td valign="middle">商品名</td>
	<td valign="middle">商品分类</td>
	<td valign="middle">广告位</td>
	<td valign="middle">加入版块</td>
	<td valign="middle">原价</td>
	<td valign="middle">现价</td>
	<td valign="middle">库存</td>
	<td valign="middle">是否上架</td>
	<td valign="middle">创建时间</td>
	<td valign="middle">最后更新时间</td>
	<td valign="middle"></td>
	
	</tr>
	<?php if($this->viewHelper->isLoop()): ?>
	<?php foreach($this->viewHelper->getSourceData() as $data): ?>
	<tr>
	<td valign="middle"><input class="table-checkbox" type="checkbox" value="<?php echo $this->viewHelper->string('product_id',$data); ?>"/></td>
	<td valign="middle"><span class="product-id"><?php echo $this->viewHelper->string('product_id',$data); ?></span></td>
	<td valign="middle"><?php echo $this->viewHelper->string('name',$data); ?></td>
	<?php $this->viewHelper->setSourceData($this->viewHelper->getProductTypeById($this->viewHelper->string('product_id',$data)),'productType'); ?>
	<td valign="middle">
		<?php if($this->viewHelper->isLoop('productType')) : ?>
		<?php foreach($this->viewHelper->getSourceData('productType') as $type) : ?>
		<span style="margin:0 5px 0 5px;"><?php echo $this->viewHelper->string('name',$type); ?></span>
		<?php endforeach; ?>
		<?php endif; ?>
	</td>
	<?php $this->viewHelper->setSourceData($this->viewHelper->getAdByProductId($this->viewHelper->string('product_id',$data)),'productAd'); ?>
	<td valign="middle">
		<?php if($this->viewHelper->isLoop('productAd')) : ?>
		<?php foreach($this->viewHelper->getSourceData('productAd') as $ad) : ?>
		<span style="margin:0 5px 0 5px;"><?php echo $this->viewHelper->string('ad_name',$ad); ?></span>
		<?php endforeach; ?>
		<?php endif; ?>
	</td>
	<?php $this->viewHelper->setSourceData($this->viewHelper->getForumByProductId($this->viewHelper->string('product_id',$data)),'productForum'); ?>
	<td valign="middle">
		<?php if($this->viewHelper->isLoop('productForum')) : ?>
		<?php foreach($this->viewHelper->getSourceData('productForum') as $forum) : ?>
		<span style="margin:0 5px 0 5px;"><?php echo $this->viewHelper->string('forum_name',$forum); ?></span>
		<?php endforeach; ?>
		<?php endif; ?>
	</td>
	<td valign="middle"><?php echo $this->viewHelper->string('original_price',$data); ?></td>
	<td valign="middle"><?php echo $this->viewHelper->string('price',$data); ?></td>
	<td valign="middle"><?php echo $this->viewHelper->string('stock',$data); ?></td>
	<td valign="middle"><?php $this->viewHelper->string('is_add',$data) == 1 ? print '是' : print '否'; ?></td>
	<td valign="middle"><?php echo $this->viewHelper->dataFormatter('creat_time','Y-m-d H:i:s',$data); ?></td>
	<td valign="middle"><?php echo $this->viewHelper->dataFormatter('update_time','Y-m-d H:i:s',$data); ?></td>
	<td valign="middle">
		<a href="<?php echo $this->url('admin-product/edit',array('pId' => $this->viewHelper->string('product_id',$data))); ?>">修改</a>&nbsp;
		<a class="product-delete" data-pId="<?php echo $this->viewHelper->string('product_id',$data); ?>" href="javascript:;">删除</a>
	</td>
	</tr>
	<?php endforeach; ?>
	<?php endif; ?>
	</table>
	<form style="float:left;" id="product-delete-form" action="<?php echo $this->url('admin-product/delete'); ?>" method="post">
		<input style="margin-top:10px;" id="product-delete" type="submit" value="删除" />
	</form>
	<form style="float:left;" id="product-forum-form" action="<?php echo $this->url('admin-product/forum'); ?>" method="post">
		<?php if($this->viewHelper->isLoop('Forum')) : ?>
		<?php foreach($this->viewHelper->getSourceData('Forum') as $forum) : ?>
		<select data-formId="<?php echo $this->viewHelper->string('forum_id',$forum); ?>" class="product-forum-select" style="margin-top:10px;">
			<option value="-1"><?php echo $this->viewHelper->string('forum_name',$forum); ?>版块</option>
			<option value="1">加入此版块</option>
			<option value="0">从该版块去除</option>
		</select>
		<?php endforeach; ?>
		<?php endif; ?>
	</form>
	<div style="clear:both;" ></div>
	<div style="margin-top:10px;" id="paging-div">
		<?php if($this->paging->isFirstPage) : ?>
		<a href="<?php echo $this->url('admin-product/index',array('pageNum' => 1)); ?>">第一页</a>
		<?php endif;?>
		<?php foreach($this->paging->numList as $num) : ?>
		<?php if($this->paging->isNow($num)) : ?>
		<?php echo $num;?>
		<?php else :?>
		<a href="<?php echo $this->url('admin-product/index',array('pageNum' => $num)); ?>"><?php echo $num; ?></a>
		<?php endif; ?>
		<?php endforeach;?>
		<?php if($this->paging->isLastPage) : ?>
		<a href="<?php echo $this->url('admin-product/index',array('pageNum' => $this->paging->getPages())); ?>">最后一页</a>
		<?php endif;?>
		总页数&nbsp;<?php echo $this->paging->getPages(); ?>
	</div>
</div>

<script type="text/javascript" language="JavaScript">
$(document).ready(function (){
	var lang=$("#ad_lang").val();
	$(".rick #page_contents_main #table_for_opration tr:gt(0) td").css({'color':'#666'});
	check_box_bind($(":checkbox[id=\"cba\"]"),$(":checkbox[id!=\"cba\"]"));
	$('.product-delete').on('click',function(){
		var _this = $(this);
		if(confirm("删除确认")){
			var pId = $(this).attr('data-pId');
			$.ajax({ url: '<?php echo $this->url('admin-product/delete'); ?>'+pId, success: function(data){
		        if(data == 'true') {
		        	_this.parent().parent().remove();
			    }
		      }
			});
		}
	});
	$('#product-delete').on('click',function(){
		if(confirm("删除确认")){
			$('.table-checkbox').each(function(){
				if(this.checked == true) {
					$('#product-delete-form').append('<input name="delete[]" type="hidden" value="'+$(this).val()+'" />');
				}
			});	
			$('#product-delete-form').submit();
		}
	});
	$('.product-forum-select').on('change',function(){
		var selectValue = $(this).val();
		var forumId = $(this).attr('data-formId');
		if(confirm("版块操作确认") && selectValue != '-1'){
			$('.table-checkbox').each(function(){
				if(this.checked == true) {
					$('#product-forum-form').append('<input name="product[]" type="hidden" value="'+$(this).val()+'" />');
				}
			});
			$('#product-forum-form').append('<input name="forumSelect" type="hidden" value="'+selectValue+'" />');
			$('#product-forum-form').append('<input name="pageNum" type="hidden" value="'+<?php echo $this->pageNum; ?>+'" />');
			$('#product-forum-form').append('<input name="formId" type="hidden" value="'+forumId+'" />');
			$('#product-forum-form').submit();	
		}		
	});
});
</script>