<p id="admin-nav"><a lang="loginTitle" href="<?php echo $this->url('admin-index'); ?>"></a>--<a lang="news" href="<?php echo $this->url('admin-news'); ?>"></a>--<span lang="newsSub"></span></p>
<div id="admin-show-div">
	<table class="admin-table">
		<tr>
			<td lang="title" class="trTitle"></td>
			<td><?php echo $this->viewHelper->string('news_title'); ?></td>
		</tr>
		<tr>
			<td lang="body" class="trTitle"></td>
			<td><?php echo $this->viewHelper->string('news_body'); ?></td>
		</tr>
	</table>
</div>