<p id="admin-nav"><a lang="loginTitle" href="<?php echo $this->url('admin/index'); ?>"></a>--<a lang="news" href="<?php echo $this->url('admin/news'); ?>"></a>--<span lang="newsAdd"></span></p>
<?php echo $this->partial('admin/common/formErrorMessage',array('errorMessages' => $form->getMessages())); ?>
<?php $form->prepare();?>
<?php echo $this->form()->openTag($form); ?>
	<table class="news-table">
		<tr>
			<td lang="title"></td>
			<td><?php echo $this->formInput($form->get('news_title')) ?></td>
		</tr>
		<tr>
			<td lang="body"></td>
			<td>
				<script id="editor" type="text/plain" style="width:820px;height:500px;">
				<?php echo $form->get('news_body')->getValue(); ?>
     			</script>
			</td>
		</tr>
	</table>
	<?php echo $this->formRow($form->get('news_botton')) ?>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.all.min.js"> </script>
<script type="text/javascript" charset="utf-8" src="/js/ueditor/lang/zh-cn/zh-cn.js"></script>
<script type="text/javascript" src="/js/admin/news_add.js"></script>