<?php echo $this->viewHelper->string(false,$errorMessage,false,array('before' => '<p>','after' => '</p>')); ?>
<form action="<?php echo $this->url; ?>" method="post">
	<input name="name" type="text" value="<?php echo $this->viewHelper->string('name'); ?>" />
	<select name="parent_id">
		<option value="0">无</option>
		<?php if($this->viewHelper->isLoop('typeParentList')): ?>
		<?php foreach($this->viewHelper->getSourceData('typeParentList') as $data): ?>
		<option <?php echo $this->viewHelper->select('ptype_id',$this->viewHelper->string('parent_id'),$data) ?> value="<?php echo $this->viewHelper->string('ptype_id',$data); ?>"><?php echo $this->viewHelper->string('name',$data); ?></option>
		<?php endforeach; ?>
		<?php endif; ?>
	</select>
	<input type="submit" value="确定" />
</form>