<p id="admin-nav"><a lang="loginTitle" href="<?php echo $this->url('admin-index'); ?>"></a>--<a lang="page" href="<?php echo $this->url('admin-page'); ?>"></a>--<span lang="pageAdd"></span></p>
<?php echo $this->partial('admin/common/errorMessage',array('viewHelper' => $this->viewHelper,'loopName' => 'errorMessage')); ?>
<form id="page-form" action="<?php echo $this->url; ?>" method="post">
	<table class="admin-table">
		<tr>
			<td lang="pageTitle"></td>
			<td><input name="page_title" value="<?php echo $this->viewHelper->string('page_title'); ?>" /></td>
		</tr>
		<tr>
			<td lang="pageBody"></td>
			<td>
				<script id="editor" type="text/plain" style="width:820px;height:500px;">
				<?php echo $this->viewHelper->string('page_body'); ?>
     			</script>
			</td>
		</tr>
	</table>
	<input id="page-submit" type="button" />
</form>
<script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.all.min.js"> </script>
<script type="text/javascript" charset="utf-8" src="/js/ueditor/lang/zh-cn/zh-cn.js"></script>
<script type="text/javascript" src="/js/admin/page_add.js"></script>