<p id="admin-nav"><a href="<?php echo $this->url('admin-index'); ?>">首页</a>--<span>页面</span></p>
<div id="page_contents_main">
	<?php if($this->viewHelper->isLoop()): ?>
	<table cellspacing="0" id="table_for_opration">
	<tr>
	<td valign="middle"><input type="checkbox" id="cba" /></td>
	<td valign="middle">页面标题名</td>
	<td valign="middle">创建时间</td>
	<td valign="middle">最后更新时间</td>
	<td valign="middle"></td>
	</tr>
	<?php foreach($this->viewHelper->getSourceData() as $data): ?>
	<tr>
	<td valign="middle"><input class="table-checkbox" type="checkbox" value="<?php echo $this->viewHelper->string('page_id',$data); ?>"/></td>
	<td valign="middle"><?php echo $this->viewHelper->string('page_title',$data); ?></td>
	<td valign="middle"><?php echo $this->viewHelper->dataFormatter('create_time','Y-m-d H:i:s',$data); ?></td>
	<td valign="middle"><?php echo $this->viewHelper->dataFormatter('update_time','Y-m-d H:i:s',$data); ?></td>
	<td valign="middle">
	    <a href="<?php echo $this->url('admin-page/edit',array('pId' => $this->viewHelper->string('page_id',$data))); ?>">修改</a>
	    <a href="<?php echo $this->url('admin-page/show',array('pId' => $this->viewHelper->string('page_id',$data))); ?>">查看</a>
	</td>
	</tr>
	<?php endforeach; ?>
	</table>
	<?php endif; ?>
	<form id="delete-form" action="<?php echo $this->url('admin-page/delete') ?>" method="post">
		<input id="delete-button" style="margin-top:10px;" type="button" value="删除" />
	</form>
	<?php echo $this->partial('admin/common/paging',array('paging' => $this->paging,'routerName' => 'admin-page')); ?>
</div>
<script type="text/javascript" src="/js/admin/page_index.js"></script>