<p id="admin-nav"><a href="<?php echo $this->url('admin-index'); ?>">首页</a>--<a href="<?php echo $this->url('admin-page'); ?>">页面</a>--<span>页面查看</span></p>
<div id="admin-show-div">
	<table class="admin-table">
		<tr>
			<td class="trTitle">标题</td>
			<td><?php echo $this->viewHelper->string('page_title'); ?></td>
		</tr>
		<tr>
			<td class="trTitle">内容</td>
			<td><?php echo $this->viewHelper->string('page_body'); ?></td>
		</tr>
	</table>
</div>