<p id="admin-nav"><a lang="loginTitle" href="<?php echo $this->url('admin-index'); ?>"></a>--<a lang="page" href="<?php echo $this->url('admin-page'); ?>"></a>--<span lang="pageShow"></span></p>
<div id="admin-show-div">
	<table class="admin-table">
		<tr>
			<td lang="pageTitle" class="trTitle"></td>
			<td><?php echo $this->viewHelper->string('page_title'); ?></td>
		</tr>
		<tr>
			<td lang="pageBody" class="trTitle"></td>
			<td><?php echo $this->viewHelper->string('page_body'); ?></td>
		</tr>
	</table>
</div>