<p id="admin-nav"><a lang="loginTitle" href="<?php echo $this->url('admin/index'); ?>"></a>--<span lang="news"></span></p>
<div id="page_contents_main">
	<?php if($this->viewHelper->isLoop()): ?>
	<table cellspacing="0" id="table_for_opration">
	<tr>
	<td valign="middle"><input type="checkbox" id="cba" /></td>
	<td lang="title" valign="middle"></td>
	<td lang="createTime" valign="middle"></td>
	<td lang="updateTime" valign="middle"></td>
	<td valign="middle"></td>
	</tr>
	<?php foreach($this->viewHelper->getSourceData() as $data): ?>
	<tr>
	<td valign="middle"><input class="table-checkbox" type="checkbox" value="<?php echo $this->viewHelper->string('news_id',$data); ?>"/></td>
	<td valign="middle"><?php echo $this->viewHelper->string('news_title',$data); ?></td>
	<td valign="middle"><?php echo $this->viewHelper->dataFormatter('create_time','Y-m-d H:i:s',$data); ?></td>
	<td valign="middle"><?php echo $this->viewHelper->dataFormatter('update_time','Y-m-d H:i:s',$data); ?></td>
	<td valign="middle">
	    <a lang="edit" href="<?php echo $this->url('admin/news/edit',array('nId' => $this->viewHelper->string('news_id',$data))); ?>"></a>
	    <a lang="show" href="<?php echo $this->url('admin/news/show',array('nId' => $this->viewHelper->string('news_id',$data))); ?>"></a>
	</td>
	</tr>
	<?php endforeach; ?>
	</table>
	<form id="delete-form" action="<?php echo $this->url('admin/news/delete') ?>" method="post">
		<input id="delete-button" style="margin-top:10px;" type="button" />
	</form>
	<?php endif; ?>
	<?php echo $this->partial('admin/common/paging',array('paging' => $this->paging,'routerName' => 'admin/news')); ?>
</div>
<script type="text/javascript" src="/js/admin/news_index.js"></script>