<select id="product-type-linkage-main" class="product-type-linkage">
	<option value="-1">无</option>
	<?php if($this->viewHelper->isLoop()): ?>
	<?php foreach($this->viewHelper->getSourceData() as $data): ?>
	<option value="<?php echo $this->viewHelper->string('ptype_id',$data); ?>"><?php echo $this->viewHelper->string('name',$data); ?></option>
	<?php endforeach; ?>
	<?php endif; ?>
</select>

<script type="text/javascript">
$(document).ready(function(){
	$('body').on('change','.product-type-linkage',function(){
		var _this = $(this);
		var productTypeId = $(this).val();
		$.ajax({ url: '<?php echo $this->url('product-type-linkage'); ?>'+productTypeId, dataType:'json', success: function(data){
			if(_this.attr('id') == 'product-type-linkage-main') {
				_this.next('.product-type-linkage-zi').remove();
			}
			else {
				_this.parent().find('.product-type-linkage-zi').remove();
			}
	        if(data != false) {
				var html = false;
				$.each(data,function(key,value){
					html += '<option value="'+value.ptype_id+'">'+value.name+'</option>';
				});
				if(html != false) {
					html = '<select class="product-type-linkage-zi" name="ptypeId[]">' + html + '<select name="ptypeId[]">';
				}
				_this.after(html);
		    }
	        else {
		        _this.attr('name','ptypeId[]');
		    }
	      }
		});
	});
});
</script>
