<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Paging\Module'                        => __DIR__ . '/Module.php',
    'Paging\Controller\PagingController' => __DIR__ . '/src/Paging/Controller/PagingController.php',
    'PagingTest\Framework\TestCase'        => __DIR__ . '/tests/Paging/Framework/TestCase.php',
    'PagingTest\SampleTest'                => __DIR__ . '/tests/Paging/SampleTest.php',
);
