<p id="admin-nav"><a href="<?php echo $this->url('admin-index'); ?>">首页</a>--<a href="<?php echo $this->url('admin-query'); ?>">询问</a>--<span>询问查看</span></p>
<div id="admin-show-div">
	<table class="admin-table">
		<tr>
			<td class="trTitle">询问人</td>
			<td><?php echo $this->viewHelper->string('q_name'); ?></td>
		</tr>
		<tr>
			<td class="trTitle">询问人电话</td>
			<td><?php echo $this->viewHelper->string('q_tel'); ?></td>
		</tr>
		<tr>
			<td class="trTitle">询问人邮件</td>
			<td><?php echo $this->viewHelper->string('q_email'); ?></td>
		</tr>
		<tr>
			<td class="trTitle">标题</td>
			<td><?php echo $this->viewHelper->string('q_title'); ?></td>
		</tr>
		<tr>
			<td class="trTitle">内容</td>
			<td><?php echo $this->viewHelper->string('q_body'); ?></td>
		</tr>
	</table>
</div>