<p id="admin-nav"><a lang="loginTitle" href="<?php echo $this->url('admin-index'); ?>"></a>--<a lang="query" href="<?php echo $this->url('admin-query'); ?>"></a>--<span lang="querySub"></span></p>
<div id="admin-show-div">
	<table class="admin-table">
		<tr>
			<td lang="queryRen" class="trTitle"></td>
			<td><?php echo $this->viewHelper->string('q_name'); ?></td>
		</tr>
		<tr>
			<td lang="tel" class="trTitle"></td>
			<td><?php echo $this->viewHelper->string('q_tel'); ?></td>
		</tr>
		<tr>
			<td lang="mail" class="trTitle"></td>
			<td><?php echo $this->viewHelper->string('q_email'); ?></td>
		</tr>
		<tr>
			<td lang="title" class="trTitle"></td>
			<td><?php echo $this->viewHelper->string('q_title'); ?></td>
		</tr>
		<tr>
			<td lang="body" class="trTitle"></td>
			<td><?php echo $this->viewHelper->string('q_body'); ?></td>
		</tr>
	</table>
</div>