<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>500</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta name="author" content="" />
<link href="/css/c1.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/js/jsq/jquery-1.10.2.min.js" language="JavaScript"></script>
<script type="text/javascript" src="/js/pt/png_ie6_fix.js" language="JavaScript"></script>
<script type="text/javascript" src="/js/glb.js" language="JavaScript"></script>
<script type="text/javascript" src="/js/lang/message.js" language="JavaScript"></script>
<script type="text/javascript" src="/js/lang/lang.js" language="JavaScript"></script>
</head><body><div class="rick"><div id="center">
<!-------------------------------------------------------------------tag_contents_start-->

<!--header_start-->
<div id="header">
<div id="log"><a href="/admin"><img /></a></div>
<div id="opration_box_header">
<div class="line0">
<span class="zp10"><select id="ad_lang">
<option value="0" selected="selected">日本語版</option>
<option value="1">中文版</option>
</select></span>
</div>
</div><br clear="all" />
</div>

<!--main_start-->
<div id="error-div">
	<p lang="String500"></p><br/>
	<a lang="Link404" href="<?php echo $this->url('admin-index'); ?>"></a>
</div>
	<?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
	<hr/>
	<h2><?php echo 'Additional information' ?>:</h2>
	<h3><?php echo get_class($this->exception); ?></h3>
	<dl>
	    <dt><?php echo 'File' ?>:</dt>
	    <dd>
	        <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
	    </dd>
	    <dt><?php echo 'Message' ?>:</dt>
	    <dd>
	        <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
	    </dd>
	    <dt><?php echo 'Stack trace' ?>:</dt>
	    <dd>
	        <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
	    </dd>
	</dl>
	<?php
	    $e = $this->exception->getPrevious();
	    if ($e) :
	?>
	<hr/>
	<h2><?php echo 'Previous exceptions' ?>:</h2>
	<ul class="unstyled">
	    <?php while($e) : ?>
	    <li>
	        <h3><?php echo get_class($e); ?></h3>
	        <dl>
	            <dt><?php echo 'File' ?>:</dt>
	            <dd>
	                <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
	            </dd>
	            <dt><?php echo 'Message' ?>:</dt>
	            <dd>
	                <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
	            </dd>
	            <dt><?php 'Stack trace' ?>:</dt>
	            <dd>
	                <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
	            </dd>
	        </dl>
	    </li>
	    <?php
	        $e = $e->getPrevious();
	        endwhile;
	    ?>
	</ul>
	<?php endif; ?>
	
	<?php else: ?>
	
	<h3><?php echo 'No Exception available' ?></h3>
	
	<?php endif ?>

<!--foot_start-->
<div id="foot_box">
<div id="foot">
copyright&nbsp;(c)&nbsp;2008&nbsp;-&nbsp;2014&nbsp;<a href="/admin" target="index">http://cn.81hp.net</a>&nbsp;All&nbsp;rights&nbsp;reserved&nbsp;/
created&nbsp;by&nbsp;<span lang="footerTitle" id="foot_company_name"></span>
</div>
</div>
</div></div></body></html>