<div id="page_list_main">

<div id="navigation">
<p lang="productTitle" data-ul="product" class="selected"></p>
<p lang="typeTitle" data-ul="type"></p>
<p lang="orderTitle" data-ul="order"></p>
<p lang="pageTitle" data-ul="page"></p>
<p lang="queryTitle" data-ul="query"></p>
<p lang="userTitle"></p>
<br clear="all" />
</div>

<div id="AdTopMenuB">
	<ul id="AdTopMenu" class="product">
		<li><p><a lang="productSub" href="<?php echo $this->url('admin-product'); ?>"></a></p></li>
		<li><p><a lang="productSubAdd" href="<?php echo $this->url('admin-product/add'); ?>"></a></p></li>
		<br clear="all" />
	</ul>
	<ul id="AdTopMenu" class="type" style="display:none;">
		<li><p><a lang="typeSub" href="<?php echo $this->url('admin-product-type'); ?>"></a></p></li>
		<li><p><a lang="typeSubAdd" href="<?php echo $this->url('admin-product-type/add'); ?>"></a></p></li>
		<br clear="all" />
	</ul>
	<ul id="AdTopMenu" class="order" style="display:none;">
		<li><p><a lang="orderSub" href="<?php echo $this->url('admin-order'); ?>"></a></p></li>
		<br clear="all" />
	</ul>
	<ul id="AdTopMenu" class="page" style="display:none;">
		<li><p><a lang="pageSub" href="<?php echo $this->url('admin-page'); ?>"></a></p></li>
		<li><p><a lang="pageAdd" href="<?php echo $this->url('admin-page/add'); ?>"></a></p></li>
		<br clear="all" />
	</ul>
	<ul id="AdTopMenu" class="query" style="display:none;">
		<li><p><a lang="querySub" href="<?php echo $this->url('admin-query'); ?>"></a></p></li>
		<br clear="all" />
	</ul>
</div>

</div>
<script type="text/javascript" language="JavaScript">
$(document).ready(function (){
	var lang=$("#ad_lang").val();
	/*---top_menu_starts---*/
	$(".rick #page_list_main #navigation p").eq(0).css('border-left','1px solid #999');
	$(".rick #page_list_main #navigation p[class!=\"selected\"]").css('background-image','url(/img/p1.jpg)');
	$(".rick #page_list_main #navigation p[class!=\"selected\"]").css({'cursor':'pointer','color':'#666'});
	hv_bg($(".rick #page_list_main #navigation p[class!=\"selected\"]"),'/img/p1h.jpg','/img/p1.jpg');
	/*---menu_second_floor_starts---*/
	hv_bg($("#AdTopMenu >li > p"),'/img/admin/p1h.gif','/img/admin/p1.gif');
	hv_color($("#AdTopMenu >li >p"),'#00E100','#00AE00');
    $('#AdTopMenuB a').css('text-decoration','none').css('color','#00AE00');
	$('#navigation p').on('click',function(){
		$('#AdTopMenuB ul').each(function(){
			$(this).css('display','none');
		});
		$('.'+$(this).attr('data-ul')).css('display','inline');
		$('#navigation p').each(function(){
			$(this).removeAttr('class');
		});
		$(this).attr('class','selected');
	});
});
</script>