<form id="login-form" action="<?php echo $this->url(); ?>" method="post">
<div id="page_login_main">
<div id="login">
<table cellspacing="0">
<tr>
<td class="td0" valign="middle"><p><img /></p></td>
<td class="td1" valign="middle"><div class="divCode" id="divCode"><span></span><span ></span><span ></span><span ></span></div><div id="codeChange" class="divCode"><a id="codeChangeA" href="javascript:;">IDpassチェンジ</a></div></td>
</tr>
<tr>
<td class="td0" valign="middle"><p><img /></p></td>
<td class="td1" valign="middle"><div class="box"><input name="uname" id="uname" type="text" /></div></td>
</tr>
<tr>
<td class="td0" valign="middle"><p><img /></p></td>
<td class="td1" valign="middle"><div class="box"><input name="pwd" id="pwd" type="password" /></div></td>
</tr>
<tr>
<td class="td0" valign="middle"><p><img /></p></td>
<td class="td1" valign="middle"><div class="box"><input type="text" id="validateCode" /></div></td>
</tr>
</table>
<div id="button_submit"><img /></div>
</div>
</div>
</form>
<script type="text/javascript" src="/js/admin/login.js"></script>