<form id="login-form" action="<?php echo $this->url(); ?>" method="post">
<div id="page_login_main">
<div id="login">
<table cellspacing="0">
<tr>
<td class="td0" valign="middle"><p><img /></p></td>
<td class="td1" valign="middle"><div class="box"><span id="valid_box"></span><span id="valid_startor">IDpassチェンジ</span></div></td>
</tr>
<tr>
<td class="td0" valign="middle"><p><img /></p></td>
<td class="td1" valign="middle"><div class="box"><input name="uname" id="uname" type="text" /></div></td>
</tr>
<tr>
<td class="td0" valign="middle"><p><img /></p></td>
<td class="td1" valign="middle"><div class="box"><input name="pwd" id="pwd" type="password" /></div></td>
</tr>
<tr>
<td class="td0" valign="middle"><p><img /></p></td>
<td class="td1" valign="middle"><div class="box"><input type="text" /></div></td>
</tr>
</table>
<div id="button_submit"><img /></div>
</div>
</div>
</form>
<script type="text/javascript" language="JavaScript">
$(document).ready(function (){
	var lang=$("#ad_lang").val();
	/*-------------login_script_start-----------*/
	$(".rick #page_login_main #login table .td0 p img").each(function (key){
		var num=key+1;
		$(this).prop('src','/img/login_text/Lang'+lang+'/c'+num+'.png');
	});
	hv_color($(".rick #page_login_main #login table .td1 #valid_startor"),'#00E100','#00AE00');
	$(".rick #page_login_main #login #button_submit img").prop('src','/img/login_text/Lang'+lang+'/c.png');
	$(".rick #page_login_main #login #button_submit").click(function (){$('#login-form').submit()});
});
</script>