<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AdminIndex\Module'                        => __DIR__ . '/Module.php',
    'AdminIndex\Controller\AdminIndexController' => __DIR__ . '/src/AdminIndex/Controller/AdminIndexController.php',
//     'AdminIndexTest\Framework\TestCase'        => __DIR__ . '/tests/AdminIndex/Framework/TestCase.php',
//     'AdminIndexTest\SampleTest'                => __DIR__ . '/tests/AdminIndex/SampleTest.php',
);
