<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Front\Module'                        => __DIR__ . '/Module.php',
    'Front\Controller\FrontController' => __DIR__ . '/src/Front/Controller/FrontController.php',
    'FrontTest\Framework\TestCase'        => __DIR__ . '/tests/Front/Framework/TestCase.php',
    'FrontTest\SampleTest'                => __DIR__ . '/tests/Front/SampleTest.php',
);
