<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Index\Module'                        => __DIR__ . '/Module.php',
    'Index\Controller\IndexController' => __DIR__ . '/src/Index/Controller/IndexController.php',
    'IndexTest\Framework\TestCase'        => __DIR__ . '/tests/Index/Framework/TestCase.php',
    'IndexTest\SampleTest'                => __DIR__ . '/tests/Index/SampleTest.php',
);
