<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AdminQuery\Module'                        => __DIR__ . '/Module.php',
    'AdminQuery\Controller\AdminQueryController' => __DIR__ . '/src/AdminQuery/Controller/AdminQueryController.php',
//     'AdminQueryTest\Framework\TestCase'        => __DIR__ . '/tests/AdminQuery/Framework/TestCase.php',
//     'AdminQueryTest\SampleTest'                => __DIR__ . '/tests/AdminQuery/SampleTest.php',
);
